// console/src/screens/AuditScreen.tsx
/**
 * Who changed what, when, and from what to what.
 *
 * Configuration here changes without a pull request, so this record is the
 * only remaining review -- which is why it carries the before and the after
 * rather than the fact of a change. Escalations are filterable rather than
 * findable by reading: "what got more permissive, and who did it" is the
 * question this screen exists for.
 */

import { useState } from "react";

import { api } from "../api/client";
import { KindBadge } from "../components/Badges";
import { Loaded, Panel } from "../components/DataState";
import { formatTime } from "../components/format";
import type { ChangeKind } from "../api/types";
import { useResource } from "../hooks/useResource";

const FILTERS: (ChangeKind | "all")[] = ["all", "escalation", "refused", "applied"];

export function AuditScreen() {
  const audit = useResource(() => api.audit(), []);
  const [filter, setFilter] = useState<ChangeKind | "all">("all");

  return (
    <Panel
      title="Audit"
      description="Append-only. Nothing in this console can edit or remove an entry."
      actions={
        <div className="row row--tight">
          {FILTERS.map((kind) => (
            <button
              key={kind}
              type="button"
              className={`button button--quiet${filter === kind ? " button--on" : ""}`}
              onClick={() => setFilter(kind)}
            >
              {kind}
            </button>
          ))}
        </div>
      }
    >
      <Loaded resource={audit} empty="Nothing has been changed yet.">
        {(entries) => {
          const shown = entries.filter((e) => filter === "all" || e.kind === filter);
          if (shown.length === 0) return <p className="muted">No {filter} changes.</p>;
          return (
            <table className="table">
              <thead>
                <tr>
                  <th>When</th>
                  <th>Operator</th>
                  <th>Setting</th>
                  <th>Before</th>
                  <th>After</th>
                  <th>Kind</th>
                </tr>
              </thead>
              <tbody>
                {shown.map((entry, index) => (
                  <tr
                    key={`${entry.at}-${entry.setting}-${index}`}
                    className={entry.kind === "escalation" ? "row--mutating" : undefined}
                  >
                    <td>{formatTime(entry.at)}</td>
                    <td>{entry.operator}</td>
                    <td>
                      <code>{entry.setting}</code>
                      {entry.reason ? <p className="muted">{entry.reason}</p> : null}
                    </td>
                    <td className="cell-value">{entry.before ?? <span className="muted">—</span>}</td>
                    <td className="cell-value">{entry.after ?? <span className="muted">—</span>}</td>
                    <td>
                      <KindBadge kind={entry.kind} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          );
        }}
      </Loaded>
    </Panel>
  );
}

// console/src/views/screens/AuditScreen.svelte
<!--
  Who changed what, when, and from what to what. Append-only: nothing in this
  console can edit or remove an entry.
-->
<script lang="ts">
  import { onMount } from "svelte";

  import { formatTime } from "../../domain/format";
  import { FILTERS } from "../../viewmodels/audit.svelte";
  import type { ConsoleVM } from "../../viewmodels/console.svelte";
  import KindBadge from "../components/KindBadge.svelte";
  import Loaded from "../components/Loaded.svelte";
  import Panel from "../components/Panel.svelte";

  let { app }: { app: ConsoleVM } = $props();

  // svelte-ignore state_referenced_locally
  const vm = app.audit();
  onMount(() => void vm.load());
</script>

<Panel title="Audit" description="Append-only. Nothing in this console can edit or remove an entry.">
  {#snippet actions()}
    <div class="row row--tight">
      {#each FILTERS as kind (kind)}
        <button
          type="button"
          class="button button--quiet{vm.filter === kind ? ' button--on' : ''}"
          onclick={() => vm.show(kind)}
        >
          {kind}
        </button>
      {/each}
    </div>
  {/snippet}
  <Loaded resource={vm.audit} empty="Nothing has been changed yet.">
    {#if vm.shown.length === 0}
      <p class="muted">No {vm.filter} changes.</p>
    {:else}
      <table class="table">
        <thead>
          <tr>
            <th>When</th>
            <th>Operator</th>
            <th>Setting</th>
            <th>Before</th>
            <th>After</th>
            <th>Kind</th>
          </tr>
        </thead>
        <tbody>
          {#each vm.shown as entry, index (`${entry.at}-${entry.setting}-${index}`)}
            <tr class={entry.kind === "escalation" ? "row--mutating" : undefined}>
              <td>{formatTime(entry.at)}</td>
              <td>{entry.operator}</td>
              <td>
                <code>{entry.setting}</code>
                {#if entry.reason}<p class="muted">{entry.reason}</p>{/if}
              </td>
              <td class="cell-value">
                {#if entry.before !== null}{entry.before}{:else}<span class="muted">—</span>{/if}
              </td>
              <td class="cell-value">
                {#if entry.after !== null}{entry.after}{:else}<span class="muted">—</span>{/if}
              </td>
              <td><KindBadge kind={entry.kind} /></td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </Loaded>
</Panel>
