// console/src/screens/StatusScreen.tsx
/**
 * Health, ingestion progress, embedding backlog, and what changed recently.
 *
 * Rendered from whatever the status endpoint reports rather than from a fixed
 * list of field names. The contract fixes the categories, not the fields
 * inside them, and the failure of hard-coding guessed names is silent: a card
 * of dashes where the number an operator came here for should be.
 *
 * Counts and timings only. Nothing on this screen is corpus content, and
 * there is no endpoint here that could return any.
 */

import { api } from "../api/client";
import type { JsonValue } from "../api/types";
import { Loaded, Panel } from "../components/DataState";
import { KindBadge } from "../components/Badges";
import { formatRelative, formatValue, humanise, partition } from "../components/format";
import { useResource } from "../hooks/useResource";

function Metrics({ entries }: { entries: [string, JsonValue][] }) {
  if (entries.length === 0) return <p className="muted">Nothing reported.</p>;
  return (
    <dl className="metrics">
      {entries.map(([key, value]) => (
        <div key={key} className="metric">
          <dt>{humanise(key)}</dt>
          <dd>{formatValue(value)}</dd>
        </div>
      ))}
    </dl>
  );
}

function Group({ name, value }: { name: string; value: JsonValue }) {
  const { scalars, groups } = partition(value);
  return (
    <Panel title={humanise(name)}>
      <Metrics entries={scalars} />
      {groups.map(([key, nested]) => (
        <div key={key} className="subgroup">
          <h3>{humanise(key)}</h3>
          <Metrics entries={partition(nested).scalars} />
        </div>
      ))}
    </Panel>
  );
}

function RecentChanges() {
  const audit = useResource(() => api.audit(), []);
  return (
    <Panel title="Recent changes" description="The last configuration changes, newest first.">
      <Loaded resource={audit} empty="No configuration has been changed yet.">
        {(entries) => (
          <ul className="changes">
            {entries.slice(0, 8).map((entry, index) => (
              <li key={`${entry.at}-${entry.setting}-${index}`}>
                <KindBadge kind={entry.kind} />
                <span className="changes__setting">{entry.setting}</span>
                <span className="muted">
                  {entry.operator} · {formatRelative(entry.at)}
                </span>
              </li>
            ))}
          </ul>
        )}
      </Loaded>
    </Panel>
  );
}

export function StatusScreen() {
  const status = useResource(() => api.status(), []);
  return (
    <>
      <Loaded resource={status}>
        {(report) => {
          const { scalars, groups } = partition(report);
          return (
            <>
              {scalars.length > 0 ? (
                <Panel title="Health">
                  <Metrics entries={scalars} />
                </Panel>
              ) : null}
              {groups.map(([name, value]) => (
                <Group key={name} name={name} value={value} />
              ))}
            </>
          );
        }}
      </Loaded>
      <RecentChanges />
    </>
  );
}

// console/src/views/screens/StatusScreen.svelte
<!--
  Health, ingestion progress, embedding backlog, and what changed recently.
  The template for every other screen: the view asks the console for its
  view-model, loads it on mount, and only renders what the view-model holds.
-->
<script lang="ts">
  import { onMount } from "svelte";

  import { formatRelative, humanise } from "../../domain/format";
  import type { ConsoleVM } from "../../viewmodels/console.svelte";
  import KindBadge from "../components/KindBadge.svelte";
  import Loaded from "../components/Loaded.svelte";
  import Metrics from "../components/Metrics.svelte";
  import Panel from "../components/Panel.svelte";

  let { app }: { app: ConsoleVM } = $props();

  // The console is built once and never replaced, so its first value is the value.
  // svelte-ignore state_referenced_locally
  const vm = app.status();
  onMount(() => void vm.load());
</script>

<Loaded resource={vm.report}>
  {#if vm.health.length > 0}
    <Panel title="Health"><Metrics entries={vm.health} /></Panel>
  {/if}
  {#each vm.groups as group (group.name)}
    <Panel title={humanise(group.name)}>
      <Metrics entries={group.metrics} />
      {#each group.subgroups as subgroup (subgroup.name)}
        <div class="subgroup">
          <h3>{humanise(subgroup.name)}</h3>
          <Metrics entries={subgroup.metrics} />
        </div>
      {/each}
    </Panel>
  {/each}
</Loaded>

<Panel title="Recent changes" description="The last configuration changes, newest first.">
  <Loaded resource={vm.audit} empty="No configuration has been changed yet.">
    <ul class="changes">
      {#each vm.recent as entry, index (`${entry.at}-${entry.setting}-${index}`)}
        <li>
          <KindBadge kind={entry.kind} />
          <span class="changes__setting">{entry.setting}</span>
          <span class="muted">{entry.operator} · {formatRelative(entry.at)}</span>
        </li>
      {/each}
    </ul>
  </Loaded>
</Panel>
