// console/src/components/ConfirmButton.tsx
/**
 * A destructive action that takes two clicks, in place.
 *
 * Not `window.confirm`: a native dialog is dismissed by muscle memory and
 * says nothing about what is being removed. This changes the button's own
 * label to name the consequence, which puts the question where the pointer
 * already is. Enabling a state-changing tool does not use this -- that needs
 * the typed gate, and a button you can click twice is not one.
 */

import { useState } from "react";

export function ConfirmButton({
  label,
  confirmLabel,
  busy,
  onConfirm,
}: {
  label: string;
  confirmLabel: string;
  busy?: boolean;
  onConfirm: () => void;
}) {
  const [armed, setArmed] = useState(false);
  if (!armed) {
    return (
      <button
        type="button"
        className="button button--quiet"
        disabled={busy === true}
        onClick={() => setArmed(true)}
      >
        {label}
      </button>
    );
  }
  return (
    <span className="row row--tight">
      <button
        type="button"
        className="button button--danger"
        disabled={busy === true}
        onClick={() => {
          setArmed(false);
          onConfirm();
        }}
      >
        {confirmLabel}
      </button>
      <button type="button" className="button button--quiet" onClick={() => setArmed(false)}>
        Keep
      </button>
    </span>
  );
}

// console/src/views/components/ConfirmButton.svelte
<!--
  A removal that takes two clicks, in place. The armed button names the
  consequence; "Keep" disarms it. See `viewmodels/confirmation.svelte.ts`.
-->
<script lang="ts">
  import { Confirmation } from "../../viewmodels/confirmation.svelte";

  let {
    label,
    confirmLabel,
    busy = false,
    onConfirm,
  }: { label: string; confirmLabel: string; busy?: boolean; onConfirm: () => void } = $props();

  const confirmation = new Confirmation();
</script>

{#if !confirmation.armed}
  <button type="button" class="button button--quiet" disabled={busy} onclick={confirmation.arm}>
    {label}
  </button>
{:else}
  <span class="row row--tight">
    <button
      type="button"
      class="button button--danger"
      disabled={busy}
      onclick={() => confirmation.confirm(onConfirm)}
    >
      {confirmLabel}
    </button>
    <button type="button" class="button button--quiet" onclick={confirmation.disarm}>Keep</button>
  </span>
{/if}
